apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-webapp-template
resources:
  - ../../base
images:
  - name: ffribeiro/python-webapp-template
    newTag: "8e8d48a6d33d78bff1fe0407d60289d02535fb0e"
