apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-webapp-template
resources:
  - ../../base
images:
  - name: ffribeiro/python-webapp-template
    newTag: "3c9a7b5fc9eb2d0a8772f54ab2fd1b291a473bf0"
