apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-webapp-template
resources:
  - ../../base
images:
  - name: ffribeiro/python-webapp-template
    newTag: "a9cbcd406cb3ba38c480edd811d69048547fbc22"
