apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-webapp-template
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rftecpro-ai/python-webapp-template.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: python-webapp-template

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
